matrix: 
  include:
    - language: python
      python:
      - "3.8-dev"
      cache: pip
      
      install:
        - pip install -r requirements.txt
       

    - language: node_js
      node_js:
      - "14"
      - "15"
      before_install:
        - cd instagram/frontend
      install: 
        - npm install
